version: "3.8"
services:
  yeasy:
    image: yeasy/simple-web
    networks:
      mreza:
        ipv4_address: 172.19.0.3
  HTMLstranica:
    image: yeasy/simple-web
    networks:
      mreza:
        ipv4_address: 172.19.0.4
  httpd:
    image: yeasy/simple-web
    networks:
      mreza:
        ipv4_address: 172.19.0.6
  loadBalancer:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./conf:/etc/nginx/conf.d:ro
    networks:
      mreza:
        ipv4_address: 172.19.0.5
networks:
  mreza:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16